
---
pipeline_dir: '/beagle3/haky/users/temi/projects/TFXcan-snakemake'
runname: 'standing_height' # change this variable name 
date: "2025-01-10" #"2024-06-07" "2024-09-23"
metadata: "/beagle3/haky/users/temi/projects/TFXcan-snakemake/metadata/metadata_standing_height.txt"
scratch_dir: "/scratch/midway3/temi"
delete_enformer_outputs: False # should you delete enformer predictions after aggregating them? Saves disk space
personalized_predictions: True # should you run personalized predictions?
runSusie: False

enpact_weights: /beagle3/haky/users/temi/projects/Enpact/files/ENPACT_734_2024-07-26.compiled_weights.lambda.1se.txt.gz

genome:
  fasta: "/project2/haky/Data/hg_sequences/hg38/Homo_sapiens_assembly38.fasta"

rscript: "/beagle3/haky/users/shared_software/TFXcan-pipeline-tools/bin/Rscript"

finemapping:
  # genotypes: "/project2/haky/Data/1000G/formatted_geno/all_chrs.geno.txt.gz"
  # snp_annot: '/project2/haky/Data/1000G/formatted_geno/all_chrs.snp_annot.txt.gz'
  # samples: "/project2/haky/Data/1000G/formatted_geno/samples.text_dosages.txt"
  LD_blocks: "/beagle3/haky/users/temi/projects/TFXcan-snakemake/metadata/EUR_LDBlocks.hg38.updated.bed"
  genotypes_dosages_pattern: '/project2/haky/Data/1000G/population_data/EUR/bfiles/ALL.chr{}.shapeit2_integrated_SNPs_v2a_27022019.GRCh38.phased.geno.txt.gz'

predictdb:
  blacklist_regions: /beagle3/haky/users/temi/projects/TFXcan-snakemake/metadata/HLA_blocks.txt
  conda_environment: /beagle3/haky/users/temi/software/conda_envs/predictdb-env
  nextflow_main_executable: /beagle3/haky/users/temi/projects/TFXcan-snakemake/workflow/PredictDb-nextflow/main.nf

summaryTFXcan:
  conda_environment: /beagle3/haky/users/temi/software/conda_envs/imlabtools
  summaryXcan_executable: /beagle3/haky/users/temi/software/MetaXcan/software/SPrediXcan.py # this is the SPrediXcan.py script

# plink:
#   folder: "/project2/haky/Data/1000G/plink_ref_panel"
#   basename: "ALL.chr{}.shapeit2_integrated_SNPs_v2a_27022019.GRCh38.phased"

enformer: 
  base_directives: "config/enformer_base.yaml"
  personalized_directives: "config/personalized_base.yaml"
  model: "/project2/haky/Data/enformer/raw"
  predict: "/beagle3/haky/users/temi/projects/TFXcan-snakemake/workflow/enformer/enformer_predict.py"
  aggregate: "workflow/src/aggregate.py"
  aggtype: "aggByCollect"
...
