
---
pipeline_dir: '/project2/haky/temi/projects/TFXcan-snakemake'
runname: 'Asthma_GWAS' # change this variable name 
date: "2024-01-31"
metadata: "/project2/haky/temi/projects/TFXcan-snakemake/metadata/metadata_gwas.txt"
scratch_dir: "/scratch/midway3/temi"
delete_enformer_outputs: False # should you delete enformer predictions after aggregating them? Saves disk space
personalized_predictions: True # should you run personalized predictions?

enpact_models:
  directory: '/project2/haky/temi/projects/TFPred-snakemake/output/models'
  filters: 
    date: "2023-12-01"
    type: "logistic"

genome:
  fasta: "/project2/haky/Data/hg_sequences/hg38/Homo_sapiens_assembly38.fasta"

rscript: "/beagle3/haky/users/shared_software/TFXcan-pipeline-tools/bin/Rscript"

finemapping:
  genotypes: "/project2/haky/Data/1000G/formatted_geno/all_chrs.geno.txt.gz"
  snp_annot: '/project2/haky/Data/1000G/formatted_geno/all_chrs.snp_annot.txt.gz'
  samples: "/project2/haky/Data/1000G/formatted_geno/samples.text_dosages.txt"
  LD_blocks: "/project2/haky/Data/LD_blocks/hg38/EUR/hg38_fourier_ls-all.bed"

plink:
  folder: "/project2/haky/Data/1000G/plink_ref_panel"
  basename: "ALL.chr{}.shapeit2_integrated_SNPs_v2a_27022019.GRCh38.phased"

enformer: 
  base_directives: "config/enformer_base.yaml"
  personalized_directives: "config/personalized_base.yaml"
  model: "/project2/haky/Data/enformer/raw"
  predict: "/beagle3/haky/users/shared_pipelines/enformer_pipeline_aggregate/scripts/enformer_predict.py"
  aggregate: "/beagle3/haky/users/shared_pipelines/enformer_pipeline_aggregate/scripts/aggregate/aggregate.py"
  aggtype: "aggByCollect"
...
